### PR TITLE
User has many interactions

### PR DESCRIPTION
**Pull request by sam-kim**
adjusted tests and added migration column to interactions

### CODE REVIEW

**Comment by westmd23** [comment]
@samk1013 way to add a partial for @user :shipit:

**Comment by mikewesthub** [comment]
@samk1013 conflicts to resolve in the schema.

**Comment by mikewesthub** [comment]
:shipit:

**Comment by bobutcher** [comment]
"Your attitude, not your aptitude, will determine your altitude."

**Pull request merged**
